baseurl = "/"
title = "gzs.fyi"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "native"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Griffin Z. Solot-Kehl"
    info = "Developer Advocate"
    description = "Griffin's personal website"
    keywords = "blog,developer,personal,devrel"
    avatarurl = "images/me.png"
    dateformat = "January 2, 2006"
    inverted = true

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/WingofaGriffin/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/griffinzs/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/WingofaGriffin/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
# [[menu.main]]
#     name = "Blog"
#     weight = 2
#     url = "/blog/"